server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RicardoDahmer/MicroService_Aula.git
          default-label: main
          search-paths:
          - 'configs/{application}'
          #username: teste
          #password: teste
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
